### ISSUE TITLE
Error with one pipeline causes all to fail

### ISSUE THREAD

**Issue by boatmisser** [tomzo/gocd-yaml-config-plugin#112]
Not sure if this is a plugin issue, or a gocd one; but I'd thought I'd ask.

When there are multiple pipelines in a YAML file, or there are multiple YAML files in a single repository; then when any single pipeline has an issue, nothing in that repository appears to be loaded.

For instance:
I have a repository with 2 YAML config files; each file has 3 pipelines.
If the second pipeline in the second YAML file has an issue (E.g. referring to a material that is not defined) then no pipeline, in either YAML file is loaded, even if all the other pipelines are fine.

Shouldn't one pipeline at time be merged so that if there are multiple pipelines all valid configurations are loaded and only the failures rejected. 

Thanks

**Comment by tomzo** [comment]
Hi,

Sorry, but that's by design in GoCD. Pipelines can depend on each other and we just don't support partially valid configurations because that would be very hard to implement with low benefits.
Still if you had pushed pipelines one by one in separate commits, the ones which were valid in the beginning would be still in GoCD when invalid commit eventually comes in. Which is why I recommend to add pipelines one by one to config repos.
