### ISSUE TITLE
Add authorization to pipeline group

### ISSUE THREAD

**Issue by tallnato** [tomzo/gocd-yaml-config-plugin#24]
It would be nice to have the authorization section in the yaml config file.
Not sure if this is something hard to implement or not.

More info
https://docs.gocd.io/current/configuration/configuration_reference.html#authorization

**Comment by tomzo** [comment]
Hi @tallnato 

We did consider it when planning https://github.com/gocd/gocd/issues/1133 . The fact that you cannot define authorization section was a design decision due to following:
 * you can have more than one config repo and there seems to be no reasonable method to merge authorization elements. If there is a conflict, what should be preferred then, granting access or not?
 * config repo may be temporarily unavailable and there is no way for server to know what is correct authorization for pipeline group. E.g. right after start.

Also consider that basically it opens a hole in security. Because any config repo can define authorization to any group. As long as developer has access to git with in config-repos section, he may just push a commit adding access.

I am going to close this. However if you feel strongly about implementing it, open an issue on https://github.com/gocd/gocd/issues . 95% of work is needed there.
