### ISSUE TITLE
improve error message when group exists but with different letter capitalization

### ISSUE THREAD

**Issue by FredrikWendt** [tomzo/gocd-yaml-config-plugin#44]
Given a gocd server
And a pipeline A is added in group Group1
When a pipeline B is added in group group1
Then Group1 should contain pipelines: A, B

However, right now, when pipeline B is read by the plugin, the error presented in GoCD server "Error" section (the red button in top right corner), shows:

`2+ errors :: Group with name 'infrastructure' already exists;; Group with name 'infrastructure' already exists;; - Config-Repo: ssh://git@gitlab.server:5522/infrastructure/gitlab-gocd-bridge.git at 0ca596f5d7a1c3860faabec41ae3b17f87f105a6`

Problem: group name is case-sensitive, but the error message doesn't say anything about that.

**Comment by tomzo** [comment]
Hi @FredrikWendt,
Thanks for the bug report. Although, the fix is a bit different than what you suggest. This error should not appear at all, because group names should be case-insensitive. This should be fixed on server side so that the case you mentioned passes with no error:
>  pipeline A is added in group Group1
When a pipeline B is added in group group1
Then Group1 should contain pipelines: A, B
