### ISSUE TITLE
add support for config-repos

### ISSUE THREAD

**Issue by jasontrublu** [tomzo/gocd-yaml-config-plugin#60]
Hi,

can we add support for the tags config-repos and config-repo so that we can defined new repositories outside the main server xml?

**Comment by tomzo** [comment]
Hi,

1. The short answer is `rather no`. Because it would be too much recursion to deal with on the server side. It is technically possible, but I don't think it is the right approach.
2. Please note that there is [config-repos API](https://api.gocd.org/current/#config-repo). So if you want to configure the list of config-repos in some repository rather than via UI/XML, you could write a script that will get current list, compare it with your list in repo and then add/remove elements to sync the two.
