### ISSUE TITLE
Apply yaml pipeline immediately using api

### ISSUE THREAD

**Issue by tpidor** [tomzo/gocd-yaml-config-plugin#65]
Hi,

I've been trying to poke gocd api to apply the yaml pipeline immediately after I pushed to config-repo, but always getting the error below. Polling works, it's just that I can't keep waiting for the polling to update the pipeline.
```
curl -u 'tpidor:*******' 'http://***********:8153/go/api/material/notify/git' -H 'Confirm: true' -X POST -d "repository_url=git@********/tpidor/gocd_pipeline_****.git" 
```
log -
```
Unable to find material. Materials must be configured not to poll for new changes before they can be used with the notification mechanism.
```

This is in config xml -
```
    <config-repo plugin="yaml.config.plugin">
      <git url="git@**********:tpidor/gocd_pipeline_****.git" branch="test_branch_poc" />
    </config-repo>
```

Tried curl as well as mentioned in #20 but no luck.
```
http://**************:8153/go/api/material/notify/git/?repository_url=git@*************:tpidor/gocd_pipeline_****.git
```
Result: The url [ /go/api/material/notify/git ] you are trying to reach doesn't appear to be correct.

By the way, GoCD version = 16.8.
Anything I missed here? Appreciate any help. Thanks.

**Comment by tomzo** [comment]
Your configuration looks fine, but your server is too old. The hooks support was added in `16.9` in this [commit](https://github.com/gocd/gocd/pull/2193/commits/7c5117f77f89e3a80153ff3d8b56f274d5c958f7).
You'll need to upgrade. BTW, `16.x` is very old, there were many fixes since then for config-repo stuff. I'd recommend that you use as new release as possible.

**Comment by tpidor** [comment]
Thanks.
Good job with the yaml plugin by the way.
