### ISSUE TITLE
Manual polling trigger

### ISSUE THREAD

**Issue by pollier** [tomzo/gocd-yaml-config-plugin#74]
Hello,
First, thanks for this great plugin :)

Would it be possible to get a manual UI button to force config repo polling ?

It would be handy to iterate quicker when building pipeline.

Thank you

**Comment by makelkal** [comment]
Hi! 

I also have this problem. Also it would be nice to see what conf is used by the stages when pipeline is already started (I have long pipelines...).

**Comment by tomzo** [comment]
@pollier Firstly any request for UI would be for gocd core https://github.com/gocd/gocd/issues 
Secondly to force polling immediately you should probably setup material webhooks https://api.gocd.org/current/#notify-git-materials

@makelkal that makes sense, but also an issue for all config repos in the [core](https://github.com/gocd/gocd/issues). As a workaround currently you can pipeline config using [API](https://api.gocd.org/current/#get-pipeline-config), the `origin` section will contain commit of the material which was used for current config.

I am closing this since it is out of scope for the yaml plugin.
